### ISSUE TITLE
I would like to see 2 more "generic" templates in the applications section. Only "password" and only "username "+"password" .

### ISSUE THREAD

**Issue by eusonlito** [eusonlito/Password-Manager#64]
I would like to see 2 more "generic" templates in the applications section. Only "password" and only "username "+"password" .

For example, if I want to store the password for a ZIP file, the password for a PFX certificate or similar, I have hardly any possibility to do so. 

Also the pure storage of e.g. system wide service accounts is difficult. Currently, one can help out with the WIFI template, but the somewhat misappropriated. 

We noticed in everyday life that we miss these two generic templates, because not all passwords have a URL, IP or similar.

_Originally posted by @JSXRED in https://github.com/eusonlito/Password-Manager/discussions/63_

**Comment by eusonlito** [comment]
@JSXRED pushed to `master`.

**Comment by JSXRED** [comment]
Thank you for this. I can confirm that the new templates are working, but i had some trouble with the upgrade.
 
Also after the upgrade all "custom" icons are gone. no big deal we just had 2 but something was fishy.
![image](https://user-images.githubusercontent.com/10437799/226469717-1a06f306-5b2d-46d6-b4b0-df7739f44820.png)

At our enviorment the .env-file was still stored at /var/www/passwordmanager and in the new container the /app/.env was always the default one. I run ./docker/build.sh to upgrade. I fixed it now manually but looks like when it comes from an older version the upgrade has some issues.

**Comment by JSXRED** [comment]
i'm not quite sure, possibly i caused a hiccup because i don't start via ./docker/run.sh. I started directly with "docker-compose up -d". Can not otherwise find any errors everything looks good and works. I could try to get the virtual machine from the backup to see if I can reproduce this, but think the effort is too high since I didn't follow the instructions exactly. As long as no one else complains we live with it I would suggest :). I'll get back to you on the next update ;).

**Comment by JSXRED** [comment]
since the "git checkout ." it is the original from the repo. i would suggest we close the ticket and if it shows up in the next update i open a new one and analyze the problem.
